# Generated by Django 2.2.1 on 2019-06-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0002_auto_20190603_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=10),
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=10),
        ),
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=10),
        ),
        migrations.AddField(
            model_name='sku',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=10),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=10),
        ),
    ]
