# Generated by Django 2.2.1 on 2019-06-04 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0003_auto_20190603_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='name',
        ),
    ]
